---

- name: Locate Downloaded Images
  stat: path={{ os_imgs[item].dest }}/{{ os_imgs[item].url | basename }}
  register: f
  with_items: "{{ os_imgs }}"
  when: os_imgs[item].url is defined

- name: Download Images
  get_url: url={{ os_imgs[item.item].url }} dest={{ os_imgs[item.item].dest }}
  with_items: "{{ f.results }}"
  when: os_imgs[item.item].url is defined and item.stat.exists == False
  loop_control:
    label: "{{ item.item }}"

- name: Uploading Images
  os_image:
    cloud: "{{ os_cloud }}"
    name: "{{ item }}"
    filename: "{{ os_imgs[item].file }}"
    properties: "{{ os_imgs[item].properties | default({}) }}"
  with_items: "{{ os_imgs }}"
