---

- os_image:
    cloud: "{{ os_cloud }}"
    name: "{{ item }}"
    filename: "{{ os_imgs[item].file }}"
    properties: "{{ os_imgs[item].properties | default({}) }}"
  with_items: "{{ os_imgs }}"
